### ISSUE TITLE
Utvide med "Godkjent status" i Begrepskatalog

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/concept-catalog-gui#257]
Se design:
https://eggedosis.github.io/fdk-design/redirects/register/dataset/section-approve-publish.html

- [ ] Oppdatere backend med ny status
- [ ] Oppdatere design

**Comment by KjerstiSteien** [comment]
Dekkes av andre statuser etter at vi gikk over til å bruke statuser fra euvoc sin kodeliste.
