### ISSUE TITLE
Begrepsregistrering: ugyldig path

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/concept-catalog-gui#434]
Hvem: bruker, alle tilgangsnivå

Hva: Modifikasjon av path i begrepskatalog (`/<orgId>/<conceptId>`)

Hva skjer:
Ved endring av orgId* -> innloggingen blir ugyldiggjort, og du kastes ut til påloggingsvinduet for registreringsløsningen
Ved endring av conceptId-> frontend forsøker å behandle pathen som "Legg til ny begrepsbeskrivelse", men redigeringssiden er helt tom

*Hvis du er logget inn som systemadmin, kan du skrive inn hva som helst som orgnr, og frontend forsøker å vise en tom katalog. Hvis orgnr er gyldig, vil orgnr bli slått opp og du vises en tom katalog med korrekt navn. Katalogen blir _ikke_ opprettet i backend, og du har ingen anledning til å legge inn begrep.

Ønsket adferd:

**Comment by jeffreiffers** [comment]
Not applicable anymore
