### ISSUE TITLE
Språk

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/concept-catalog-gui#478]
### Feature beskrivelse
Bilde:
![image](https://user-images.githubusercontent.com/50879748/219086027-495ae435-7250-45b6-923d-4a57f731464a.png)

GUI + filtreringslogikk: motta brukerinput via sjekkbokser, og filtrer trefflisten basert på valgene.

Lenke til skisse:  
https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=1159%3A41103&viewport=520%2C695%2C0.5&scaling=scale-down-width

### Hvorfor trenger vi det?
Lenke til brukerhistorie:
https://github.com/Informasjonsforvaltning/behov/issues/806 

### Forslag/løsning [Valgfritt]
sjekk om dette er løst et annet sted og om noe kan gjenbrukes, ellers "be creativ"!

### Definisjon av ferdig
?

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Etter diskusjon med Breg og Skatt har vi landet på at vi ikke ønsker å støtte filtrering på språk ennå. Det er for uklart hva kriteriene for denne filtreringen skal være. Lukker derfor denne saken.
