### ISSUE TITLE
Merkelapp

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/concept-catalog-gui#479]
### Feature beskrivelse
Bilde:
![image](https://user-images.githubusercontent.com/50879748/226314521-911aeaed-d7b8-4832-b66f-932d4443206f.png)

GUI + filtreringslogikk: trefflisten skal filtrerers når det trykkes på på disse merkelappene.

Lenke til skisse:  
https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=1159%3A41103&viewport=520%2C695%2C0.5&scaling=scale-down-width

### Hvorfor trenger vi det?
Lenke til brukerhistorie:
https://github.com/Informasjonsforvaltning/behov/issues/806 

### Forslag/løsning [Valgfritt]
sjekk om dette er løst et annet sted og om noe kan gjenbrukes, ellers "be creativ"!

### Definisjon av ferdig
?

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by KjerstiSteien** [comment]
Vi venter med denne i første omgang. I stedet ønsker vi at man skal kunne trykke på merkelapper i trefflista og at dette fører til filtrering på merkelappen man har trykket på. @pooriamehregan endrer du beskrivelsen av saken? @NilsOveTen er det støtte for dette i backend?

**Comment by NilsOveTen** [comment]
Atm er det bare støtte for filtrering på status, jeg la til merkelapp her: https://github.com/Informasjonsforvaltning/concept-catalog/issues/142

**Comment by NilsOveTen** [comment]
@KjerstiSteien er merkelapp et internt felt eller skal vi legge det til for alle?
