### ISSUE TITLE
Sortering

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/concept-catalog-gui#481]
### Feature beskrivelse
Bilde:
![image](https://user-images.githubusercontent.com/50879748/219083206-98c2a397-e8f5-49c8-984a-4593750e3b4f.png)

GUI + filtreringslogikk: motta brukerinput via nedtrekksmenyen, og filtrer trefflisten basert på valget.

Lenke til skisse:  
https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=1159%3A41103&viewport=520%2C695%2C0.5&scaling=scale-down-width

### Hvorfor trenger vi det?
Lenke til brukerhistorie:
https://github.com/Informasjonsforvaltning/behov/issues/806 

### Forslag/løsning [Valgfritt]
sjekk om dette er løst et annet sted og om noe kan gjenbrukes, ellers "be creativ"!

### Definisjon av ferdig
?

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

**Comment by hegeaal** [comment]
@matfuru Filter og nedtrekk

**Comment by pooriamehregan** [comment]
@KjerstiSteien @matfuru lurer på omd dere vet hva kan en sortere på, er det kun rekkefølgen sånn type stigende/synkende, eller skal set også være mulig å sortere på felter. Hvis sisnevnte er ønskelig, synes at det blir rar hvis alle sorteringsalternativer skal vise i en select-boks.

**Comment by KjerstiSteien** [comment]
@pooriamehregan Dette er det jeg har notert som ønsket å sortere på: Alfabetisk (stigende), Alfabetisk (synkende), Sist endret-dato (stigende), Sist endret-dato (synkende)
