### ISSUE TITLE
Forretningsbegrep (spesielt for Skatt)

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/concept-catalog-gui#516]
Filter for boolsk verdi med navn Forretningsbegrep. Skal kun være synlig for Skatt
- [x] #529
- [x] Frontend logic for Forretningsbegrep

**Comment by pooriamehregan** [comment]
Blokkert:
- backend, samt logikk på frontend trenger avklaringer før de implementeres

**Comment by jeffreiffers** [comment]
Erstattet av filter på internefelt
