### ISSUE TITLE
Feature: Fjern kommentarfelt fra redigeringsside

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/concept-catalog-gui#544]
Som bruker av begrepskatalogen ønsker jeg å slippe å se kommentarer inne i selve redigeringsskjemaet, da jeg allerede får denne informasjonen på detaljsiden til begrepet. 

Oppgave: 
Fjern kommentarfelt og tilhørende knapp fra registreringsskjemaet i begrepskatalogen, og rydd opp i backend.

**Comment by jeffreiffers** [comment]
Den ligger klar til review men vi venter med å rulle ut i prod frem til nye begrepskatalogen er lansert.
