### ISSUE TITLE
Feature: Knapp eller lenke fra redigeringsskjema til detaljside

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/concept-catalog-gui#596]
Som bruker ønsker jeg å enkelt kunne navigere til detaljsiden for begrepet jeg har redigert, slik at jeg enkelt kan få oversikt over begrepet og bruke de funksjonene som finnes på detaljsiden. 

TODO: 
- [x] Lag en knapp eller lenke fra redigeringsskjema til detaljsiden for begrepet

**Comment by pooriamehregan** [comment]
Dette er lagt inni brødsmulestien nå
