### ISSUE TITLE
Endre tekst i melding ved sletting av utkast

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/concept-catalog-gui#606]
Forvirrende melding når jeg velger slett utkast: 

![image](https://github.com/Informasjonsforvaltning/concept-catalog-gui/assets/110605570/c7d1fa03-0f1b-42d0-91a9-98047f326076)

Ønsker tekst: "Bekreft at du vil slette dette utkastet."

**Comment by NilsOveTen** [comment]
Vil ikke også `utkast` være forvirrende? Kanskje `Bekreft at du vil slette denne versjonen av begrepet.`?

**Comment by jeffreiffers** [comment]
Vi har blitt enig om å fjerne slett knappen. Bruk slett på detaljvisningen.
