### ISSUE TITLE
Mulighet for å relatere til upubliserte begrep fra egen katalog

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/concept-catalog-gui#616]
Som skrivebruker i begrepskatalogen, ønsker jeg å kunne koble begrep i katalogen min til begrep i min katalog som er upubliserte. 

Hvorfor er dette viktig? 
For å ivareta arbeidsprosesser på en god måte og sikre at begreper som bør relateres til andre begrep blir relatert. 

Forslag til løsning:
Beholde dagens nedtrekksliste/søk for begrep ved relasjoner, og inkludere upubliserte begrep fra virksomheten jeg er logget inn som. 
Markere at et begrep er upublisert (trenger design)
Markere hvem som eier begrepet (sjekk om dette finnes i dag)
Ikke vise lenke til upublisert begrep i portal.

**Comment by NilsOveTen** [comment]
Søket som gjøres til fulltext er samme som brukes for autocomplete i portal, forslår at vi gjør det samme her. Dvs legger til et `suggestion`-endepunkt i backend, som kan brukes til dette søket og en eventuell autocomplete for søket i begrepskatalogen

**Comment by NilsOveTen** [comment]
søket vi brukte før vi gikk over til å søke i fulltext har blitt fjerna fra concept-catalog, så dette issuet bør nok flyttes til blocked

**Comment by NilsOveTen** [comment]
blokkert av https://github.com/Informasjonsforvaltning/concept-catalog/issues/309

**Comment by KjerstiSteien** [comment]
Designforslag: Vise om begrepet er publisert helt til høyre i listen. 

![image](https://github.com/Informasjonsforvaltning/concept-catalog-gui/assets/110605570/b7e061e6-0c28-4946-bada-2ad9d47b4fbb)

**Comment by NilsOveTen** [comment]
I tillegg til å vise publiseringsstatus tror jeg også bør vise om det er treff fra intern katalog vs treff fra FDK

**Comment by KjerstiSteien** [comment]
Lukker denne. Løst av sakene Hege lenket til i forrige kommentar.
